const num1 = 20;
const num2 = "20";

console.log( parseInt(num2) ); // parseInt(num2) -- Esto es una función
console.log( num1.toString() ); // num1.toString() -- Esto es un metodo

// NOTA: LA DIFERENCIA ENTRE FUNCION Y METODO ES QUE LA FUNCION PARA SER LLAMADA SOLO NECESITAS COLOCAR SU NOMBRE SEGUIDO DE DOS PARENTESIS, EN CAMBIO PARA LLAMAR UN METODO PRIMERO TIENES QUE LLAMAR A SU VARIABLE LUEGO COLOCAR UN PUNTO Y RECIEN SE PODRA ACCEDER AL METODO SEGUIDO DE PARENTESIS.